masterPassword: 'password'
accounts:
  - name: 'Playground'
    serverUrl: 'playground-lnd:10009'
    macaroonPath: '/root/.lnd/data/chain/bitcoin/signet/admin.macaroon'
    certificatePath: '/root/.lnd/tls.cert'
